version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: facebook
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  nodejs_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: googleforms.c6isbbs62jkt.us-east-1.rds.amazonaws.com
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: facebook
    depends_on:
      - mysql

volumes:
  mysql-data: